packages:
  - packages/*
  - "!fixtures/*"

allowBuilds:
  simple-git-hooks: true

# hoistPattern:
#   - "*"
#   - "!@types/react"

# packageExtensions:
#   antd@6:
#     peerDependencies:
#       "@types/react": "^19.0.0"
